# Generated by Django 3.1.2 on 2020-10-10 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_offered',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='service_user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service_booking_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_booked_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_user.client_user_details')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_user.service_offered')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_user.service_user_details')),
            ],
        ),
    ]
